### ISSUE TITLE
Oj.load("Infinity") => Infinity

### ISSUE THREAD

**Issue by Zelnox** [ohler55/oj#161]
This doesn’t look right.

    [3] pry(main)> Oj.load "Infinity" 
    => Infinity
    [4] pry(main)> JSON.parse "Infinity"
    JSON::ParserError: 757: unexpected token at 'Infinity'

Tested with ruby 2.0.0-p481, Oj 2.8.0 and 2.9.5

**Comment by quentindemetz** [comment]
It looks like Infinity is still present in compat mode, with the following example:
```ruby
Oj.default_options = { mode: :compat}
Oj.dump(Float::INFINITY)
=> "Infinity"
```

**Comment by ohler55** [comment]
I think I need to just flush all occurrences of Infinity on dump. Maybe leave it in for read for backwards compatibility but never dump.

**Comment by quentindemetz** [comment]
Yes, please replace it with `null` according to the spec

**Comment by ohler55** [comment]
Actually the JSON spec only says Infinity and NaN are not permitted, not to replace with null. There are a few different ways of handling that.

1. ignore those field values and don't place them in the output
2. replace those field values with null. I'd expect that with the :null mode.
3. replace with a different number that is large enough to be considered infinity such as 1.0e1000000000 or maybe larger.
4. replace with a string

There are probably other approaches but these are the first that came to mind. I lean toward 3 in general and for sure in object mode.

I just double checked and the JSON library does indeed use `Infinity` as output when dumping. I guess Oj has to output that in combat mode as well then. Given that I think option 3 is best for object mode and strict and null can stay as they are.

**Comment by quentindemetz** [comment]
I was basing myself on the fact that https://github.com/ohler55/oj/issues/230#issue-70030543 says otherwise...

It's not very clear what Rails does for Infinity, I've seen:
```ruby
Float::INFINITY.to_json
=> "Infinity"
render json: Float::INFINITY # from within a Rails controller
=> "null"
```

My issue with :null mode is that it implies :strict, which excludes :compat. I think a good option would me to move this :null behavior into new configuration field `infinity`, just as is the case with `nilnil` or `quirks_mode`.
I would suggest multiple values be possible for this configuration option:
- :null (or nil) to convert them to null values
- 42 to convert them to 42
- :default to choose a sensible default depending on the :mode parameter:
  - 1e100 for object mode if that's what you had in mind
  - either null or "Infinity" for compat mode
  - raise an exception in strict mode 

What do you think ?

**Comment by ohler55** [comment]
I don't think we are far off in our thinking. I can see changing strict and null mode to have an option for infinity and NaN becoming null instead of rising an exception. That would allow behavior similar to the ECMA stringify behavior. I'd point out that the comment referred to is for ECMA objects, not Ruby objects so it is not really relevant in this case.

So how about (almost the same as your suggestion I think):

 * a nan option that allowed either null, large number, Infinity (or similar), raise and exception, or any number explicitly like 42

That option would be available for :null, :strict, and :compat modes. :object would always use a large number.

**Comment by quentindemetz** [comment]
We're on the right path, that sounds great!

It seems like creating this new configuration option is sort-of deprecating the null mode, which should now probably be achieved through:
```ruby
Oj.default_options = {
  mode: :strict,
  nan: :null
}
```

If you are hard-coding "large number" for object, I don't really see a scenario where we want to specify a number explicitly elsewhere. Feel free to kick that option out.

**Comment by ohler55** [comment]
Null mode also replace non-core Ruby object with null. For if you have a Hash with an element that is not a Hash, Array, boolean, number, string, or nil it will be null in the output.

"large number" was meant to be a placeholder for a map of values something like this:

Infinity => 1.0e1000000000
-Infinity => -1.0e1000000000
NaN => 7.0e1000000000

What the actual numbers will be is still up in the air until I get to the implementation. Having explicit values allows to map back the other direction on loading in object mode. Not 100% safe since they could be mapped to a BigDecimal but probably ok for a large number of use cases.

**Comment by ohler55** [comment]
I just pushed a version to github with the new :nan option. The huge numbers are 3.0e14159265358979323846 and similar. The exponent is too large to be represented by a 64 bit int so it seems unlikely to collide with any value entered by a user. User are smart though so I'm sure someone will find a way. :-)

**Comment by ohler55** [comment]
Released.

**Comment by ohler55** [comment]
Ok to close?

**Comment by quentindemetz** [comment]
Yes, thanks!
