### ISSUE TITLE
Oj.dump(Float::INFINITY) should return "null"

### ISSUE THREAD

**Issue by alanho** [ohler55/oj#230]
The [ECMA-262](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf) explicitly stated
> NOTE 4 Finite numbers are stringified as if by calling ToString(number). NaN and Infinity regardless of sign are represented as the String null.

Currently
```
2.2.1 :001 > require "oj"
 => true 
2.2.1 :002 > Oj::VERSION
 => "2.12.4" 
2.2.1 :003 > Oj.dump(Float::INFINITY)
 => "Infinity"
```

"Infinity" is not a valid JSON string, and raise errors in browsers. None of the 4 modes available now allow user to generate a valid JSON. Expected result should be "null"

**Comment by ohler55** [comment]
Ar you asking for a new feature or mode?

According to the JSON spec http://json.org infinity is not a supported number in either dumping or parsing. In strict mode Oj adheres to the spec in that regard and will raise an exception if it encounters a Float::INFINITY. The same is true if it encounter the naked string Infinity in a JSON document.

Since many applications, parsers, and serializers support Infinity Oj also does in object and compat mode. The callback parsers leave that choice up to the callback function.

So I believe you are asking for a version of the parser that deviates from the JSON specification and instead is compliant with the ECMA specification. What would you think about dumping null if Oj is in :null mode instead of supporting a full ECMA mode?

**Comment by alanho** [comment]
I think your suggestion is good. Currently there is no way to dump a ECMA-compliant JSON if it encounters a Float::INFINITY. Either an exception is raised in :strict mode or "Infinity" is dumped.

So infinite value should be dumped as null in :null mode, at least a way to dump a compliant JSON without replacing these values

**Comment by ohler55** [comment]
Pushed a version to github. Let me know if it works the way you expect in :null mode.

**Comment by alanho** [comment]
Excellent. Works like a charm! Thanks for the prompt release!

I wish i can do a PR but it's a shame that I haven't wrote a single line of C since college!

**Comment by ohler55** [comment]
No problem. I'll do a release and make it official.

**Comment by quentindemetz** [comment]
I've been reading through this, but don't understand how I could profit from both:
- object mode (more flexible towards string keys, fastest, etc)
- casting Infinity to null (:null mode selects :strict automatically)

I can't switch my API to Oj because all of a sudden a bunch of "Infinity" are popping up in my JSON responses, which Chrome can't parse...

Is there a way I can get the best of both worlds ? Thanks for the great work btw!

**Comment by ohler55** [comment]
If you want Chrome to read the JSON then you probably do not want to use the object mode. Well, maybe if the format is not that important. You bring up a good point though. Object mode should generate 100% valid JSON and it is not since Infinity is not a valid JSON value. It is okay for combat mode since that is meant to be compatible with a different format that is not compliant but object mode should be compliant.

My preferred fix would be to use a very large number instead of Infinity. Maybe something like 1.0e1000000000 or something in object mode. If null is used then the original object could not be created. Would that work for you?

**Comment by quentindemetz** [comment]
Don't worry, forget about it, I'm not going to be using object mode because of #285 which I just discovered, I'll stick to strict / null mode.

**Comment by ohler55** [comment]
Added a :nan option. You now have control over how infinity and nan values are handled.
