### ISSUE TITLE
RBX support?

### ISSUE THREAD

**Issue by benlovell** [ohler55/oj#237]
I see the docs mention you support rbx but I also see you removed rbx from your build matrix and there is an issue: rubinius/rubinius#3399

Do you still intend to support rbx?

**Comment by ohler55** [comment]
I would love to support RBX. Right now it is not in the target because travis kept failing to install for testing. Locally it is not in my target since I still have not been successful install RBX with rbenv. I can try again though and see if either has changed.

**Comment by ohler55** [comment]
Still fails to install with rbenv.

**Comment by benlovell** [comment]
@ohler55 did you check out rubinius/rubinius#3399? @yorickpeterse tagged you in a comment over there.

**Comment by ohler55** [comment]
I did see it and it gives me hope. Until I can get RBX installed on either OS X or Ubuntu 14 I'm kind of stuck.

**Comment by benlovell** [comment]
Ah I see. I hate to say it but Works On My Machine :tm: I'm running yosemite. My guess is you're missing some LLVM related things.

@yorickpeterse can help you out I'm sure. :wink:

**Comment by ohler55** [comment]
I've got another VM I am trying to install from the bzip2 file. I'll see if that works. If that fails I contact @yorickpeterse.

**Comment by YorickPeterse** [comment]
@ohler55 what problems are you having with rbenv? I recall they made a bunch of changes to make things work a while ago.

**Comment by ohler55** [comment]
How about we start with OS X. This is what I get using rbenv.

eye-3 ~> rbenv install rbx-2.5.4
Downloading rubinius-2.5.4.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/ed7104f6177dc2c5be346e5a7349118601d8b0b0a37eb76fa1a78da21b3fbcfc
Installing rubinius-2.5.4...

BUILD FAILED (OS X 10.9.5 using ruby-build 20150506-2-g4dfc609)

Inspect or clean up the working tree at /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514131312.44031
Results logged to /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514131312.44031.log

Last 10 log lines:
	from /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514131312.44031/rubinius-2.5.4/.gem/gems/bundler-1.3.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514131312.44031/rubinius-2.5.4/.gem/gems/bundler-1.3.6/lib/bundler/runtime.rb:13:in `setup'
	from /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514131312.44031/rubinius-2.5.4/.gem/gems/bundler-1.3.6/lib/bundler.rb:119:in `setup'
	from /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514131312.44031/rubinius-2.5.4/.gem/gems/bundler-1.3.6/lib/bundler/setup.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.

**Comment by YorickPeterse** [comment]
Looks like you're lacking LLVM. If you're using homebrew you can either install LLVM 3.5 (unless they already removed that in favour of 3.6) or use the homebrew formulas located at https://github.com/rubinius/homebrew-apps to install a prebuilt version of Rubinius. When building from source or using rbenv, pass the `--lvm-config path/to/llvm/config` option when installing and you should be good to go.

**Comment by ohler55** [comment]
The prebuilt sounds like the ticket. I'm having a tough time getting brew setup with libssl. The current llvm from brew seems to be 4.2 after an upgrade. With the upgrade to llvm I was able to get rubinius installed. I try it out later tonight.

**Comment by ohler55** [comment]
Turns out it did not install properly. Tried again with the brew path first and it turns out the brew ruby-build is 1.9.1.

eye-3 ~> rbenv install rbx-2.5.4
Downloading rubinius-2.5.4.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/ed7104f6177dc2c5be346e5a7349118601d8b0b0a37eb76fa1a78da21b3fbcfc
Installing rubinius-2.5.4...

BUILD FAILED (OS X 10.9.5 using ruby-build 20150506-2-g4dfc609)

Inspect or clean up the working tree at /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514194443.25333
Results logged to /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514194443.25333.log

Last 10 log lines:
Installing ri documentation for bundler-1.3.6...
Installing RDoc documentation for bundler-1.3.6...
Fetching gem metadata from https://rubygems.org/..
Installing rake (10.4.2)
Installing daedalus-core (0.3.0)
Installing redcard (1.1.0)
Installing rubinius-ast (2.3.2)
Gem::InstallError: rubinius-ast requires Ruby version >= 1.9.2.
An error occurred while installing rubinius-ast (2.3.2), and Bundler cannot continue.
Make sure that `gem install rubinius-ast -v '2.3.2'` succeeds before bundling.

If I don't have /usr/local/bin as the first directory in $PATH I get the previous error about LLVM.

Any suggestions?

**Comment by ohler55** [comment]
Trying on yosemite. different problem

ohler@air-2 ~> rbenv install rbx-2.5.4 
Downloading rubinius-2.5.4.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/ed7104f6177dc2c5be346e5a7349118601d8b0b0a37eb76fa1a78da21b3fbcfc
Installing rubinius-2.5.4...

BUILD FAILED (OS X 10.10.3 using ruby-build 20150506)

Inspect or clean up the working tree at /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514205810.27403
Results logged to /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20150514205810.27403.log

Last 10 log lines:
Installing ri documentation for bundler-1.3.6...
Installing RDoc documentation for bundler-1.3.6...
Fetching gem metadata from https://rubygems.org/..
Installing rake (10.4.2) 
Installing daedalus-core (0.3.0) 
Installing redcard (1.1.0) 
Installing rubinius-ast (2.3.2) 
Gem::InstallError: rubinius-ast requires Ruby version >= 1.9.2.
An error occurred while installing rubinius-ast (2.3.2), and Bundler cannot continue.
Make sure that `gem install rubinius-ast -v '2.3.2'` succeeds before bundling.
ohler@air-2 ~> ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.1.0]

**Comment by YorickPeterse** [comment]
> Gem::InstallError: rubinius-ast requires Ruby version >= 1.9.2.

What version of Ruby are you using to install Rubinius? Also, is it possible to build from source instead of using rbenv? That way we can rule out rbenv possibly mucking with the installation process.

**Comment by ohler55** [comment]
Last line shows 1.9.3.

I'll try from source today.

**Comment by ohler55** [comment]
:-( Frustrating. I've got llvm installed and as you can see rake 10.4.2 is installed in ruby 2.2.2.

eye-3 rubinius-2.5.4> ./configure
Checking clang: found
Checking clang++: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/definition.rb:132:in `specs'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/definition.rb:177:in `specs_for'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/definition.rb:166:in `requested_specs'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/runtime.rb:13:in `setup'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler.rb:122:in `setup'
	from /Users/ohler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.8/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
eye-3 rubinius-2.5.4> gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
bundler (1.9.8)
daedalus-core (0.3.0)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
oj (2.12.7)
ox (2.2.0)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
redcard (1.1.0)
rubinius-ast (2.3.2)
rubinius-bridge (1.1.0)
rubinius-build_tools (2.0.0)
rubinius-compiler (2.3.1)
rubinius-melbourne (2.3.1.0)
rubinius-processor (2.3.0)
rubinius-toolset (2.3.1)
test-unit (3.0.8)

**Comment by YorickPeterse** [comment]
@brixen since you're an OS X user, any ideas on the above problem? I can't really tell where it's going wrong :/

**Comment by brixen** [comment]
@ohler55 sorry, but I have no ability to help with rbenv or RVM issues. There are historically too many and we can't fix those projects anyway.

I build a binary for OS X. It's easily installed with Homebrew but need to be. You can fetch the binary listed in the recipe, untar to a directory, and either exec `bin/rbx` directly or put the `bin` and `lib/rubinius/2.5.5/gems/bin` directories on PATH. If you have chruby installed, the binary will be added to `~/.rubies/` so you can use it with chruby.

The Homebrew recipe is keg-only due to conflicting with MRI, but you can `brew link --force --overwrite rubinius` and then `brew unlink rubinius` when you're done.

See https://github.com/rubinius/homebrew-apps/blob/master/rubinius-2.5.5.rb

I also build a binary for Ubuntu 14.04. See http://binaries.rubini.us/index.txt for available ones. The Ubuntu 12.04 binary is used by Travis Linux, but I could build one for Travis OS X as well. No one has ever requested one and I didn't think of that.

If you need a different binary, I'll happily build you one. It will be 1000x easier than trying to fix rbenv.

**Comment by ohler55** [comment]
Thats great. I'll give it a try tonight.

**Comment by ohler55** [comment]
Great, I can run rbx!

**Comment by benlovell** [comment]
:heart_eyes:

**Comment by ohler55** [comment]
Just two failing tests related to time and it looks like a roundoff error. I will fix the test or the code. Thank you all for helping me get moving.

**Comment by YorickPeterse** [comment]
@ohler55 Great to hear, and thanks for looking into this!

**Comment by ohler55** [comment]
Candidate release waiting. Just had to changing the rounding rules for Rubinius.

**Comment by brixen** [comment]
@ohler55 super cool, thanks for working through the issues and please ping us right away if you have problems in the future.

**Comment by ohler55** [comment]
Now that I have a rubinius binary I should be good until the next release. Thanks

**Comment by ohler55** [comment]
Release 2.12.9 includes the test fixes. Any objections to closing?

**Comment by YorickPeterse** [comment]
If things are working, go ahead. Thanks for looking into this!
