### ISSUE TITLE
rounding a float result a different float with more precisions in to_json

### ISSUE THREAD

**Issue by victor-huang** [ohler55/oj#258]
the problem in oj 2.12.12:
[1] pry(main)> a = 0.8136100000000001 
=> 0.81361
[2] pry(main)> a.round(5).to_json
=> "0.8136100000000001"

in version  2.9.3, the to_json method will return correct result "0.81361"

**Comment by ohler55** [comment]
What is the setting in the default options for the float_precision? If you want the exact Ruby formatting then set that value to zero instead of the default.

I checked the code and I have the mimic_JSON setting the value to 16 which is probably the reason for the value you are seeing. I'll change that to 15 as well to avoid the round off issues and let someone make it higher if they want.

**Comment by ohler55** [comment]
Try it with the latest 2.12.13 release.

**Comment by victor-huang** [comment]
Thanks for the fix. it works with the default setting. i will set float_precision to 0 for my use case.
btw, what's the reason not to use 0 as the default for float_precision?

**Comment by ohler55** [comment]
Ruby is slower than C. If you are trying to get the highest performance the Ruby calls reduce the performance.
