### ISSUE TITLE
Allow passing `:space` to `Oj.dump`

### ISSUE THREAD

**Issue by tt** [ohler55/oj#273]
I'm trying to figure out how to dump JSON as `"name": ...` (i.e. with a space after the colon).

I can see that the extension supports this when overriding the `JSON` module but it would be great to also allow it when using `Oj.dump` so that MultiJSON's adapter can use this when pretty formatting is desired.

**Comment by ohler55** [comment]
Well, your suggestion has me thinking. I do not want to add that one option and I don't want to add the 20 or so that would be needed to completely define how to format output for extreme control over output. Right now OJ is optimized with some flexibility for indented formatting. That works with MultiJSON today. If you were seeing a space after the colon then it was not with Oj but a different gem.

Anyway, with the aim of providing the hooks or parameters to more fully control output I'll have to give it some thought on how to provide the flexibility without breaking or slowing down the current performance. Stay tuned here or feel free to off some suggestions. The option at the top of my list would be a formatting Ruby object. That would give complete formatting control but would be much slower as it would be primarily Ruby code and not C code.

**Comment by ohler55** [comment]
Maybe the Ruby object could just be a Hash with 20 parameters for control of output and then make that an argument to a Oj.pretty_dump() method.

**Comment by tt** [comment]
I didn't mean to say that MultiJSON has an option for outputting the space but Oj itself does parse the `:space` parameter inside [the `mimic_generate_core` function](https://github.com/ohler55/oj/blob/4dbb9a859383cfc21ce374fd3f4d94567e28c2ad/ext/oj/oj.c#L1684-L1691). It's just not exposed when using `dump`.

I'm all for not exposing a lot of options and I don't need the `:space` parameter in particular but I do consider the space after the colon the de facto standard for pretty formatting. I would like to use Oj and still have that.

I could happily accept just passing a `:pretty` parameter or calling `pretty_dump`.

**Comment by ohler55** [comment]
I see what you mean now. I could probably move the few options I have there now into the defaults and also support them in dump as well as JSON.generate.

**Comment by ohler55** [comment]
I just pushed a version that adds support for the dump options that JSON generate uses. Please give it a try. If it works for you I will make a release.

**Comment by ohler55** [comment]
Ok to close?

**Comment by ohler55** [comment]
No response, closing as options were added with unit tests.
