### ISSUE TITLE
quirks mode = false works incorrectly for strings

### ISSUE THREAD

**Issue by hwo411** [ohler55/oj#284]
According to JSON specs https://tools.ietf.org/html/rfc4627#section-2.5
json is either object or array

The test covers only null value https://github.com/ohler55/oj/blob/master/test/test_various.rb#L1254
also it works correctly for numbers, but not for strings:

```ruby
[16] pry(main)> Oj.load('"1"', quirks_mode: false)
=> "1"
[19] pry(main)> Oj.load("\"1\"", quirks_mode: false)
=> "1"
```

There should be raised an `Oj::ParseError `.
Could you fix it please?

**Comment by ohler55** [comment]
A little background first. Oj was built be consistent with the JSON definition as defined at json.org and ECMA-404. Those definitions are less restrictive about the top level JSON value and the IETF interpretation which restricts the top level JSON value to an object or an array. To allow developers to restrict the parsing to the IETF definition the quirks_mode was added.

You are right in that the quirks_mode is not working as it is supposed to and I will get a fix in so that strings are not allowed either. Additional unit tests will be added to cover the condition as well. I should have the fix out today but it might take a little longer is I get behind in the schedule.

**Comment by hwo411** [comment]
@ohler55 I love this idea to be able to parse a non-object value, but in my case I used oj with `oj_mimic_json` and I needed full compatibility with `JSON.parse` and that's how I actually found this bug.

Thank you for fixing this so quickly!

**Comment by ohler55** [comment]
Good to close the issue?
