### ISSUE TITLE
:time_format not respected

### ISSUE THREAD

**Issue by brian-vogogo** [ohler55/oj#295]
```ruby
Oj::VERSION
# => "2.15.0"
Oj.dump(Time.current, mode: :compat, time_format: :unix)
# => "\"2016-04-01T22:33:51.992Z\""
```
I expected to see `"1459550076"`.

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

**Comment by ohler55** [comment]
Works fine for me using plain Ruby.

```ruby
irb(main):001:0> Oj.dump(Time.now, mode: :compat, time_format: :unix)
=> "1459551172.947467000"
```

Since current is only available when using Rails I suspect that is what you are using. Probably have active installed as well and you are running into the to_json methods that active monkey patches on each object. You can try using Oj.mimic_JSON or use the Oj option :use_to_json => false to inhibit the active to_json patch.

**Comment by brian-vogogo** [comment]
Yeah it definitely Rails related. Tried it in a nearly new Rails 4.2.4 project and see the same problem. Works in irb. Oj.mimic_JSON and :use_to_json => false didn't help. 

We are probably going to solve our problem a different way. Feel free to close this issue. I can try other options if you'd like. Thanks!

**Comment by ohler55** [comment]
That’s my preferred mode as well.
