### ISSUE TITLE
:time_format option ignored after Oj.mimic_JSON

### ISSUE THREAD

**Issue by cschlack** [ohler55/oj#355]
```ruby
> Oj.dump({ time: Time.now }, mode: :compat, time_format: :xmlschema)
=> "{\"time\":\"2017-03-24T10:51:35.941245000+01:00\"}"
> Oj.mimic_JSON
=> JSON
> Oj.dump({ time: Time.now }, mode: :compat, time_format: :xmlschema)
=> "{\"time\":{\"json_class\":\"Time\",\"s\":1490349106,\"n\":906983000}}"

**Comment by ohler55** [comment]
Hold off on this please. I am working on a 3.0 release. In that version compat mode will mimic the json gem and will not use the Oj option. There will be a new rails mode to mimic rails and finally a new custom mode that lets you fiddle with all the options. I expect the 3.0 will be out next week some time.

**Comment by ohler55** [comment]
The 3.0 release is not yet ready but I can tell you that in mimic json you will not have th echoice to change the time format as the json gem does not allow that other than changing the to_json() method. You will be able to change the format in the new custom mode. Otherwise the compat/json mode will be just like the json gem and the rails mode will be just like the activesupport encoder and parser. Both tested with the latest unit test from the respective component.

**Comment by ohler55** [comment]
Please check the Oj 3.0 release.

**Comment by masterkain** [comment]
sorry for the dumb question: starting with version 3 do we just need to include the gem in a rails project and oj will start automatically to be used or do we need to specify a `format: :rails` somewhere? thanks.

**Comment by ohler55** [comment]
Check the page on Oj and Rails http://www.ohler.com/oj/doc/file.Rails.html. You will need to include those 4 lines in your Rails setup.

**Comment by ohler55** [comment]
Ok to close?

**Comment by ohler55** [comment]
No response. With the complete change to Rails and son gem support this is no longer a valid issue.
