### ISSUE TITLE
Lint code with Rubocop

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/oj#405]
Hi,
What's your stance on using Rubocop to lint Ruby code?

A test-run on my system with Rubocop `0.49.1` returned 6529 offenses using their default setting.
If you're willing, then we could decide on a fixed style over multiple PRs

**Comment by ohler55** [comment]
With less than 1000 line of Ruby code I find is hard to imagine there are 6529 offenses. I'll take a look but something sounds off.

Anyway, my stance is that it might be fine for serious violations but if it is just for style then I see no need to make changes. I haven't looked at Rubocop yet so I can't say much more than that right now.

**Comment by ashmaroli** [comment]
I wouldn't call them serious violations,
The majority of these offenses are from the test files. I excluded `test/**/*` from the scan and the result is down to
```
17 files inspected, 483 offenses detected
```

**Comment by ohler55** [comment]
Ok, I haven't run Rubocop but reading the detail it seems to be mostly about style. I've never been much for enforcement of style guides. I have a consistent style and I think that is enough. I don't see the need to conform to someone else's idea of what is the right style. As long as the code is consistent and readable there is no reason to change it to follow another style. I have no problem with people having opinions on what style they like to follow but I don't see the need to change my style to something different just because they documented their preferences on a github repo. I prefer the philosophy that people should be free to chose their own path. I vote for style freedom! Set developers free. Ok, I got a little carried away there. The point is that if the code is readable and works as expected then don't worry about how many spaces are used or if one pattern is used over another.

**Comment by ashmaroli** [comment]
:smile: FYI, Rubocop is not about enforcing *their* style. It's about enforcing *your* style consistently (in future PRs) at the same time maintain readability..

The reason I opened this ticket was I saw a few areas that was confusing (to me) and thought perhaps I can have it sorted out..

**Comment by ashmaroli** [comment]
for example, I found instances of `if 0 == name.length` and some other instances of `value == variable.operation` and the normal `variable.operation == value`

**Comment by ohler55** [comment]
All the mentioned patterns are completely valid. I use ```0 == xxx``` often. It is a carry over from the C code. I see no reason to change that. As for setting up Rubocop to enforce my own style, I don't see the benefit. If a developer is not comfortable with reading code that has different elements on either side of a equals comparison swapped according to what they find normal then they probably don't have enough experience to modify the code without breaking it. That is pretty basic computer science.

**Comment by ohler55** [comment]
Getting to the point, I do not plan on reformatting the current code match a style guide whether it is defined by someone else or by me. I enjoy writing code and don't like being overly constrained in the way I express my ideas.

If you have discovered some bugs in the code or if there is a way for Rubocop to only detect bugs such as unassigned variables I would be glad to fix those types of issues and incorporate Rubocop into my work flow.

**Comment by ashmaroli** [comment]
Thank you for your response, Peter.
Closing..

**Comment by ohler55** [comment]
I apologize if I have offended your sensibilities. It was interesting to find out more about Rubocop. Thanks

**Comment by ashmaroli** [comment]
No offense taken. I'm still on board if you need a Windows user perspective while fixing AppVeyor.. :smiley:

**Comment by ohler55** [comment]
Great. I will need help with appveyor. I'll start on that again this weekend.
