### ISSUE TITLE
float rounding mistake when optimizing Rails

### ISSUE THREAD

**Issue by toaster** [ohler55/oj#448]
Oj version: 3.3.9
Ruby version: 2.3.3
Rails version: 5.0.1

```ruby
[1] pry(main)> f = -1.7976931348623157e+308
=> -1.7976931348623157e+308
[2] pry(main)> require 'rails'
=> true
[3] pry(main)> f.to_json
=> "-1.7976931348623157e+308"
[4] pry(main)> require 'oj'
=> true
[5] pry(main)> Oj.dump(f)
=> "-1.79769313486232e+308"
[6] pry(main)> Oj.default_options = {float_precision: 0}
=> {:float_precision=>0}
[7] pry(main)> Oj.dump(f)
=> "-1.7976931348623157e+308"
[8] pry(main)> Oj.optimize_rails
=> nil
[9] pry(main)> f.to_json
=> "-1.797693134862316e+308"
```

As you can see, the default Rails `to_json` does not round the number.
Oj rounds because of its `float_precision` but this can be turned of using `float_precision: 0`.
But when Oj optimizes the Rails implementation, it uses a precision independent from its `default_options` and not fully compatible to the standard Rails behaviour.

**Comment by ohler55** [comment]
I can bump up the precision for the optimized version to 17 significant digits but you will then find that the 17th digit is sometimes different. Optimization uses a different conversion from a float (C double) to a string. Any more than 16 digits will vary since the binary encoding for a float does not support more than 16 digits across all numbers. If exact behavior with rails out to 17 significant digits is more important than performance then the extra step of optimizing should not be taken.

**Comment by toaster** [comment]
Okay, I understand that.
We will skip the optimization part, then.

**Comment by ohler55** [comment]
Thanks for understanding. Float precision has been trouble for quite a while.
