### ISSUE TITLE
Do you follow SemVer? If yes, please mention in README

### ISSUE THREAD

**Issue by pravi** [ohler55/oj#464]
This will help in debian packaging and many projects have responded positively already https://wiki.debian.org/Teams/Ruby/UpstreamPledge

**Comment by ohler55** [comment]
I already do my best to follow semantic versioning and have since the project started 6 years ago. I'm not sure why it is important to make a special notice in the README.md about that. Most Ruby gems follow a semantic version release model and developers generally assume that is the case. I would be willing to make a statement that I will do my best to continue to use semantic versions when releasing but adding more clutter to the README.md does not seem like a positive change.

**Comment by pravi** [comment]
I really wish SemVer to be the case by default. But that is not the case from experience. Some projects refuse to follow SemVer and without an explicit statement from the developer, other projects assume there is no SemVer compliance. Projects like gitlab does this. So they declare oj ~> 2.17.4. So I have to maintain a patch in debian and keep it updated for every release of gitlab to be able to use a newer minor version. You can see the list of projects I talked to on this issue in my first comment and about 1 in 6 projects refuse to comply with SemVer. A statement from you will reduce maintenance burden for me and will give confidence to projects like gitlab to relax their oj requirement.

**Comment by ohler55** [comment]
Consisder my statement give as:
Oj follows semantic versioning when releasing new versions.

**Comment by ohler55** [comment]
So, is that sufficient? Can this be closed?

**Comment by ohler55** [comment]
Thanks.
