### ISSUE TITLE
Why is oj so slow?

### ISSUE THREAD

**Issue by DmitryKK** [ohler55/oj#465]
I performed measurements with Benchmark.

I have got 25 db records. And i have subclass (ShopSerializer) of Active Model Serializer. For example. My first measurement was:

### Default settings:

```ruby
shops = Shop.limit(25)
Benchmark.measure { 100.times { shops.map { |s| ShopSerializer.new(s) }.to_json }}
```
I got:

```ruby
#<Benchmark::Tms:0x007fb65cdf7108 @cstime=0.0, @cutime=0.0, @label="", @real=100.9618310000078, @stime=2.68, @total=14.44, @utime=11.76>
```

Real time is **100.9618** seconds

### Oj Settings

```ruby
Oj.mimic_JSON
shops = Shop.limit(25)
Benchmark.measure { 100.times { Oj.dump shops.map { |s| ShopSerializer.new(s) }}}
```

And then i got:

```ruby
#<Benchmark::Tms:0x007fb6608ee450 @cstime=0.0, @cutime=0.0, @label="", @real=124.19603600000846, @stime=3.26, @total=17.83, @utime=14.57>
```

Real time is **124.1960** seconds.

#### 1.23x more slowly

Seriosly? Wtf? What am I doing wrong?

**Comment by ohler55** [comment]
Its hard to tell what the call stack looks like without a bit more information. Are you using Rails? What are the default options for Oj? If Rails is being used, is he ShowWithChargesSerializer using Oj or something else? Oj has some options for tracing. Just add `trace: true` to the call to Oj.dump. If you turn them on you can get a better idea of what is being called. You could also turn on Ruby tracing.

**Comment by DmitryKK** [comment]
Yes, i'm using Rails 5. Oj has default options. My serializer is using ActiveModelSerializer for generating object. But `Oj.dump` converts it to json.

Trace:

```ruby
...
#0:dump_compat.c:932:Oj:}:   dump ShopWithChargesSerializer
#0:dump_compat.c:907:Oj:{:   dump ShopWithChargesSerializer
#0:dump_compat.c:932:Oj:}:   dump ShopWithChargesSerializer
#0:dump_compat.c:907:Oj:{:   dump ShopWithChargesSerializer
#0:dump_compat.c:932:Oj:}:   dump ShopWithChargesSerializer
...
```

**Comment by ohler55** [comment]
How does the output of to_json and Oj.dump compare? Are they the same or similar or is Oj serializing more attributes? Something else to try is using Rails mode instead of JSON mode. Try optimize for rails.

What strikes me as odd is that the trace shows dumping the ShopWithChargesSerializer but not any low level Ruby objects which it should do unless dumping ends up calling to_json or as_json which puts the encoding back into Ruby. Rails and the JSON gem have different defaults for that.

One thing I do see that would help you is adding a trace for entering a to_json or as_json call. I'll put that on the list for adding to Oj.

**Comment by ohler55** [comment]
Oj trace now shows entering and leaving `to_json` and `as_json`. I suspect that will show calling one or the other. The next step would be to see what arguments are bing used. It is possible that Oj is serializing more object attributes depending on the arguments passed.

**Comment by ohler55** [comment]
Are you interested in this thread?

**Comment by ohler55** [comment]
No interest, closing.
