### ISSUE TITLE
Date json in key of hash

### ISSUE THREAD

**Issue by sb8244** [ohler55/oj#471]
I'm unsure if this is a bug or not, but it seemed off so I wanted to report it:

```
[4] pry(main)> date = DateTime.now ; Oj.dump({date => date}, mode: :compat) 
=> "{\"2018-04-25T00:27:17-04:00\":\"2018-04-25T00:27:17.443935-04:00\"}"
[5] pry(main)> date = Time.now ; Oj.dump({date => date}, mode: :compat) 
=> "{\"2018-04-25 00:29:10 -0400\":\"2018-04-25T00:29:10.699209-04:00\"}"
```

In this case, the key does not encode to the same value as the value, even though it's the same object.

**Comment by ohler55** [comment]
There may be more than one thing going on here. First in `:compat` mode the `#to_json` methods will be called on values just like with the JSON gem. Since the default encoding is not shown in you example I can only assume there is a `#to_json` method on Time which would be the case if you were using Rails. In that case the value is determined by Rails.

The key, also a time, is encoded using the `#to_s` method to be consistent with the JSON gem when in `:compat` mode. There should be no expectation that they be the same no matter what mode you are using. The key can not be encoded using the same code as the value as the JSON spec calls for a string as the key yet values can be one of half a dozen different types.

**Comment by sb8244** [comment]
Thanks, this makes sense. I have the expectation that they would be the same as this is how the rails encoder works, at least on 4.2. However, I understand your point and can appreciate that I'll need to turn the date into appropriate json encoding first.

**Comment by sb8244** [comment]
Thanks for the quick feedback @ohler55 . I should have checked this out more.

I'm not sure why, but it *does* encode differently in my Rails app. However, `ActiveSupport::JSON.encode` and `to_json` work like Oj does in rails mode.

I worked around it by calling `as_json` on the time field before setting it into the key.

Thanks for your work.

**Comment by ohler55** [comment]
Glad you got it figured out.
