### ISSUE TITLE
Serializing Regexp objects

### ISSUE THREAD

**Issue by smanolloff** [ohler55/oj#550]
```ruby
require 'oj'
puts Oj::VERSION
# => 3.8.1
puts RUBY_VERSION
# => 2.5.5


input = {regex: /a/}
puts Oj.dump(input, mode: :custom)
# => {"regex":{"s":"(?-mix:a)"}}
```
I expect `{"regex":"(?-mix:a)"}`, what is this weird `"s"` wrapper?

It is not present in the `:compat` mode, but I can't use that since i need `bigdecimal_as_decimal: true`, which is not available there.

**Comment by ohler55** [comment]
The mode is important. Using :object mode there is a serialization that is meant to create the exact same objects when deserialized. I suspect the mode you want is the :custom mode. All options are available in that one.

**Comment by smanolloff** [comment]
I am sorry, I really could not get your point. In the eample above, I am using `:custom` mode, not `:object` mode:
```ruby
input = {regex: /a/}
puts Oj.dump(input, mode: :custom)
# => {"regex":{"s":"(?-mix:a)"}}
```

**Comment by ohler55** [comment]
My apologies. That really should have been a string. Let me look into it.

**Comment by ohler55** [comment]
I refreshed my memory. When using `:create_additions` the JSON object you are seeing is used to recreate the original object. If `:create_additions` is false then the create ID is not included. That is what you are seeing.

So, what makes the most sense? I don't want to break existing code but without the `:create_additions` set the output does seem odd. A string representation would probably be better. I think an option that checks both the `:create_additions` and also the `:create_id` for nil would be a sufficient indicator that a string representation is desired. Existing code would continue to work because the default `:create_id` is set to `json_class` by default.

What are your thoughts on that approach?

**Comment by smanolloff** [comment]
It _does_ sound like a workaround, but it will surely work for me.
I have not used the `create_additions` feature and might be unaware of the pitfalls with this solution, though.

**Comment by ohler55** [comment]
Please try the `3.9alpha` branch.

```
irb(main):001:0> Oj.dump(/hello/, mode: :custom)
=> "\"/hello/\""
```

**Comment by ohler55** [comment]
Changed it. Set `:create_id` to nil.

`Oj.dump(/hello/, mode: :custom, create_id: nil)`

**Comment by smanolloff** [comment]
Any way to get the old behaviour (2.x version)?
```ruby
irb(main):001:0> Oj.dump(/hello/, mode: :custom)
=> "\"(?-mix:a)\""
```
I am trying to update oj an existing API from 2.x to 3.x but can't really do it if regexps can't be serialized this way :/

**Comment by ohler55** [comment]
Easy enough. I thought the `#inspect` gave a more friendly output but `#to_s` is fine too.

**Comment by ohler55** [comment]
Release 3.9.0 includes the fix.

**Comment by smanolloff** [comment]
Yes, I already bumped my project's oj to 3.9.0, and it works as expected. You are the best 🍻
