### ISSUE TITLE
Rails segmentation fault when no argument is passed

### ISSUE THREAD

**Issue by Asmoddym** [ohler55/oj#565]
Rails 4.2.7.1, Ruby 2.3.3
When I type `Oj.dump()` without any parameter on a Rails console, the server segfaults.

![Screenshot 2019-10-29 at 10 32 07](https://user-images.githubusercontent.com/17594162/67754891-7b486c80-fa37-11e9-961a-0f7b68844688.png)

**Comment by ohler55** [comment]
I'll look into it. It is just supposed to raise an exception like it does when not in rails although you are using a very old version of Ruby.

**Comment by ohler55** [comment]
I was not able to install ruby 2.3.3 on macOS. I'll try on a linux machine tomorrow.

**Comment by ohler55** [comment]
No success getting 2.3.3 installed. I did have 2.3.7 installed on an older machine I could use though. By itself, without rails there is no issue. I was not able to install an older version of rails. 

What confuses me is how the console would even be able to call a function with the wrong number of arguments. More recent versions of the rails console raises an exception before even calling Oj.dump with no arguments.

I'm afraid there's not much else I can do since I can't install the versions you are running into issues with. If you are not able to upgrade you could test by trying to call another function that requires an argument with no arguments and see if the console has the same issue.

**Comment by Asmoddym** [comment]
Ok, thanks anyway! Btw, I tested this on some other functions requiring arguments, but I have the "wrong number of arguments" message.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by Asmoddym** [comment]
yep
