### ISSUE TITLE
{escape_mode: :unicode_xss} no longer escapes "<" or ">" characters since 3.7.5 in compat mode

### ISSUE THREAD

**Issue by svilenivanovsmule** [ohler55/oj#569]
Hi, 

We noticed that starting version 3.7.5, Oj no longer escapes "special" XSS characters `<` or `>` in compat mode:

```
$ gem install --version 3.7.4 --no-doc oj
Building native extensions. This could take a while...
Successfully installed oj-3.7.4
1 gem installed
$ ruby -r oj -e 'puts "#{Oj::VERSION} -> #{Oj.dump("<", {mode: :compat, escape_mode: :unicode_xss})}"'
3.7.4 -> "\u003c"
$ gem install --version 3.7.5 --no-doc oj
Fetching oj-3.7.5.gem
Building native extensions. This could take a while...
Successfully installed oj-3.7.5
1 gem installed
$ ruby -r oj -e 'puts "#{Oj::VERSION} -> #{Oj.dump("<", {mode: :compat, escape_mode: :unicode_xss})}"'
3.7.5 -> "<"
```

However, it works as before in mode `rails`:
```
$ ruby -r oj -e 'puts "#{Oj::VERSION} -> #{Oj.dump("<", {mode: :rails, escape_mode: :unicode_xss})}"'
3.7.5 -> "\u003c"
```

It seems it is related to the change in #557. I wonder if this is expected behaviour? If so, perhaps worth updating the documentation to warn about this behaviour (or crash at runtime in case of `mode`: `compat`) as it opens possibility of unexpected XSS.

Thank you for the awesome gem!

**Comment by ohler55** [comment]
That was not intentional. I didn't think there were any changed in that code. I'll check.

**Comment by ohler55** [comment]
After doing some digging here is the story:

In `:compat` mode Oj mimics the JSON gem. The JSON gem does not escape `<` or `>`. Oj does the same in `:compat` mode. Neither `:unicode_xss` nor `:xss_safe` escape mode should be honored when in `:compat` mode. Noted that they are and that is a bug. I'll make sure they are not honored. `:rails` mode does escape but there is no option to not escape. That is also intentional. The best approach would be to use the `:custom` mode if you want to deviate from either `:compat` or `:rails` modes. 

I know this is not the answer you were looking for but if I break the compatibility it will cause problems for others.

**Comment by svilenivanovsmule** [comment]
Thank you very much for the follow up, @ohler55! I will adapt our code base accordingly.
