### ISSUE TITLE
Handling NaN Values

### ISSUE THREAD

**Issue by Rambatino** [ohler55/oj#585]
Dump appears to be ignoring nan options other than word.

``` ruby
 Oj.dump(Float::NAN, nan: :word) # defualt
=> "NaN"
Oj.dump(Float::NAN, nan: :null)
=> JSON::GeneratorError: NaN not allowed in JSON.
```

Is this expected? After reading the documentation it appears that NaN should be turned to null. Or is there some config I need to set somewhere and have completely missed it from the documentation?

It works if you switch the mode to `rails`:

``` ruby
Oj.dump(Float::NAN, mode: :rails)
=> "null"
```
However, we need `compat`, or at least that's what we've been using when using V2. But:

``` ruby
 Oj.dump(Float::NAN, mode: :compat, nan: :null)
JSON::GeneratorError: NaN not allowed in JSON.
```

**Comment by ohler55** [comment]
It does depend on the mode you are in. I'll take a look later today.

**Comment by Rambatino** [comment]
I've got around it with:

``` ruby
Oj.dump(Float::NAN, mode: :rails, nan: :null)
```

I just thought if you would pass a "convert nan to this" parameter it would use that?

**Comment by Rambatino** [comment]
(In fact you don't need the {nan: :null} there as that's the default for rails mode.

**Comment by Rambatino** [comment]
On further inspection, we were using `mode: :compat` and `nan: :null` which we can't do now in V 3.0 as it will return `JSON::GeneratorError: NaN not allowed in JSON.`

**Comment by Rambatino** [comment]
@ohler55 have you had any chance to have a gander at this?

**Comment by ohler55** [comment]
It is on my list for tonight. I have been packing up for a move but am finally done.

**Comment by ohler55** [comment]
Found a few minutes. All modes other than the `:custom` mode ignore the `:nan` option as described on https://github.com/ohler55/oj/blob/develop/pages/Modes.md. For the `:compat` mode an exception is raised because that is what the JSON gem does. In `:rails` mode `"null"` is returned because that's what Rails does. If you want to break away from the JSON gem mimicking mode then the `:custom` mode is your best bet. I can not add that option to the `:compat` mode as that would break compatibility with the JSON gem which is the whole reason for that mode.

**Comment by Rambatino** [comment]
Thanks for the info @ohler55! Really appreciate you looking into this.
