### ISSUE TITLE
Using time_format and use_to_json together

### ISSUE THREAD

**Issue by beanieboi** [ohler55/oj#598]
Hey 👋

first of all, thanks for `Oj` it's a tremendous help and amazing piece of Software!

We are currently facing an issue where we can't use `time_format :ruby` `use_to_json: true` together.

Gemfile
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "activesupport", "> 6.0"
gem "oj", "> 3.0"
```

oj.rb
```ruby
require "bundler"
Bundler.setup

require "active_support/all"
require "oj"

o = {
  created_at: Time.at(1587376937), # Class: Time
  retention_time_ms: 2.weeks * 1000, # Class: ActiveSupport::Duration
}

p Oj.dump(o, {:mode=>:custom, :time_format=>:ruby, :use_to_json=>true})
p Oj.dump(o, {:mode=>:custom, :time_format=>:ruby, :use_to_json=>false})
```

expected time format (aka ruby time) `2020-04-20 12:02:17 +0200`

setting `use_to_json: true` will ignore `time_format: :ruby` the returned time format is 8601
```
p Oj.dump(o, {:mode=>:custom, :time_format=>:ruby, :use_to_json=>true})
"{\"created_at\":\"2020-04-20T12:02:17.000+02:00\",\"retention_time_ms\":1209600000}"
```

if we set `use_to_json: :false` it will respect `time_format` but `ActiveSupport::Duration` will be formatted in a wrong way.

```
p Oj.dump(o, {:mode=>:custom, :time_format=>:ruby, :use_to_json=>false})
"{\"created_at\":\"2020-04-20 12:02:17 +0200\",\"retention_time_ms\":{\"parts\":{\"weeks\":2000},\"value\":1209600000}}"
```

Is there a way to use `use_to_json: true` and also respect the `time_format` setting? Any help is appreciated.

cheers

**Comment by ohler55** [comment]
When the `:use_to_json` option the `to_json` methods on the objects are called and Oj is no longer part of the formatting while in that method. Since ActiveSupport monkey patches all objects with a to_json method you can't really expect some to be honored and some not. An approach that might work would be to replace the to_json on Time to be what you want it to be. If there is a way to remove the to_json method that would be better but I don't know how to do that.
