### ISSUE TITLE
Ruby process crash at `Oj.dump` 

### ISSUE THREAD

**Issue by sitaram-altizon** [ohler55/oj#602]
Hi, @ohler55 Thank you for this gem, it has been working great for us over the last few years.

Recently we are seeing our Sidekiq process crashing at `Oj.dump(data, compat: true)` in our code. The issue seems to be a form of accumulated value crash since after we restart the process, sidekiq runs the same code seamlessly for a few days until the next crash occurs.
To debug the issue I inspected the data that was being dumped, tried to dump it again but it worked. I also looked at docker container level CPU/Memory usage but didn't find anything obvious.

Following are some quick info about our system:
```
ruby version - 2.3.1
rails version - 5.0.0.1
sidekiq version - 5.2.8
Oj version - 3.10.2
```
Sample `data` at the time of the crash
`[{:day=> Rails:Time, :s_key=>Ruby:String}, {:day=> Rails:Time, :s_key=>Ruby:String}]`

We have a huge stack trace provided by the gem but I'm not very used to debugging ruby crashes so It'd be of great help if you can give me some pointers where can I start debugging. 
Also please feel free to ask for any other information you want from my side.

**Comment by ohler55** [comment]
I haven't found the stack traces to be very helpful in the past. My usual approach is first to recreate the issue. Since your's takes days to fail that's calls for another approach. Given that it takes so long to crash I would suspect a leak of some type (accumulated value). First suspect is memory so I would monitor and log the memory use. If it is growing that is an indication of a leak so even if memory in the container looks fine there may be times when it bounces up that you are not seeing.

I will have to look into Sidekiq a bit to see how they handle threads. If the Sidekiq jobs are using Ruby objects there could be some issues there but I'd think Sidekiq honors the Ruby global value lock.

**Comment by sitaram-altizon** [comment]
Okay, got it.
@ohler55  Thank you for your inputs.
I'll also close this issue and update if this has any relation with the Gem itself.
