### ISSUE TITLE
omit_nil for arrays

### ISSUE THREAD

**Issue by MosheZemah** [ohler55/oj#612]
Any chance there will be an option like omit_nil that currently affects only Hash, to affect also arrays 
like array.compact! in Ruby, where nil values are removed.

Thanks

**Comment by ohler55** [comment]
Omit nill is a common feature among JSON writers since the default value if something is not present is to return null or in the case of Ruby, nil. The same is not true for arrays as removing a value changes the position of items in the array and therefor the meaning. Its probably best to compact arrays before dumping or after parsing if that is the direction you are considering.

Sorry to disappoint.
