### ISSUE TITLE
DateTime renders differently in 3.11.4/5 vs 3.11.3

### ISSUE THREAD

**Issue by nuzelac** [ohler55/oj#658]
Hi,

I'm running oj with Oj.optimize_rails() and Blueprinter. When I upgraded oj to 3.11.5 dates in the output JSON started being rendered differently

oj 3.11.5:
```
      "created_at": "2019-09-20 16:17:55 UTC",
```

oj 3.11.3:
```
      "created_at": "2019-09-20T16:17:55.985Z",
```

I saw a change in 3.11.4 with Rails compatibility but I don't know what exactly affects this. Any suggestions what I can try?

**Comment by ohler55** [comment]
There was a bug in Oj.generate that cause it to act differently than the JSON gem it was trying to mimic. That was fixed in 3.11.4 and 3.11.5.  The question I has if whether the current behaviour matches the JSON gem or not. Oj has a lot of options for configuring the library so pretty much any behaviour is possible but when in compat mode it attempts to be the same as the JSON gem.

**Comment by nuzelac** [comment]
Ohhh I understand now thank you, I played with it a bit and see why the previous version was buggy. 
I need to find the solution in Blueprinter since it's calling OJ.generate and can't do `mode: :rails`.

**Comment by ohler55** [comment]
If you discover any work arounds or settings that might help others feel free to add to this issue.
