### ISSUE TITLE
Oj.load("") fails since the last release

### ISSUE THREAD

**Issue by tmaier** [ohler55/oj#667]
I used to have the following code, which worked pretty well up to now.
Since the last patch release (`3.11.7`) of Oj, this code fails

```ruby
    def self.load(hash)
      new(hash.respond_to?(:each) ? hash : Oj.load(hash.to_s))
    end

```

Error message when the `hash` is `nil`
```
Oj::ParseError: unexpected colon (after ) at line 1, column 2 [parse.c:668]
from (pry):36:in `load'
```

My work around

```ruby
    def self.load(hash)
      case hash
      when nil
        new
      when proc { |s| s.respond_to?(:each) }
        new(hash)
      else
        new(Oj.load(hash.to_s))
      end
    end
```

**Comment by ohler55** [comment]
Moving from 3.11.6 to 3.11.7 only changed the type of the parse exception when in rails mode. If I were to guess, the default mode you are using has changed to `:compat` or `:rails` instead of the `:object` mode. In the `:compat` or `:rails` modes Oj raises an exception on an empty string to be consistent with the way the JSON gem and Rails behaves.

**Comment by tmaier** [comment]
You are right. I do have `Oj.optimize_rails` in my code, but since one year.

**Comment by ohler55** [comment]
There were some fixes to the rails options a couple of versions back. Maybe that was it. I believe the current behaviour is correct for both Rails and the JSON gem now though. It is a constant struggle to walk the line as Rails and the JSON gem battle it out for control though.

**Comment by tmaier** [comment]
I See. I am closing this issue.
Thanks for your quick response and this cool gem
