### ISSUE TITLE
`symbolize_names` does not symbolise the keys like `symbol_keys` does

### ISSUE THREAD

**Issue by senhalil** [ohler55/oj#672]
Since `symbolize_names` is an alias for `symbol_keys`, I expected them to return the same object.

However, `symbolize_names` doesn't return a Hash with symbolised keys like `symbol_keys` does in the example below:
```bash
(byebug) Oj.load(Oj.dump({:abc => 123}, mode: :compat), symbol_keys: true)
{:abc=>123}
(byebug) Oj.load(Oj.dump({:abc => 123}, mode: :compat), symbolize_names: true)
{"abc"=>123}
```

**Comment by ohler55** [comment]
`symbolize_names` is not an alias for `symbol_keys`. `symbolize_names` is an option only to JSON.parse after calling Oj.mimic_JSON. Note, like the json gem that option is not available to JSON.load. Since Oj is attempting to mimic the json gem behaviour there are inconsistencies around the use of `symbolize_names` just like the json gem.

**Comment by senhalil** [comment]
Thanks for the clear explanation @ohler55 In that case, I guess the documentation needs amelioration because it says "`:symbolize_names` is an alias" in the `:symbol_keys` subsection.
 
https://github.com/ohler55/oj/blob/develop/pages/Options.md#symbol_keys-boolean

**Comment by ohler55** [comment]
Thanks, I clean up the docs.

**Comment by ohler55** [comment]
Done. http://www.ohler.com/oj/doc/file.Options.html

**Comment by senhalil** [comment]
Thanks for the rapid fix ohler55 !
